### ISSUE TITLE
Support controling additional panels on both sides of diff/compare view.

### ISSUE THREAD

**Issue by scratchee** [HexFiend/HexFiend#203]
When performing a diff/compare, you can only control which ui elements are shown for the right pane.

For example, if you use the "Views" menu to turn off line numbers, turn on the plain text view, turn on templates, turn on columns, etc. These options all only apply to the right hand pane, the left hand pane ignores them.

Seems to me the solutuon would be to have the settings apply to both sides, though I guess an alternative would be to have a duplicate sets of controls in a submenu for the left pane.

Relatedly, it'd be nice if these ui settings were remembered for the diff/compare view.

**Comment by lpla** [comment]
Hello. Any progress on this? I am very interested in seeing the plain text view in both sides when comparing two files.

**Comment by kainjow** [comment]
Initial support for this has been added in 8eb80ad484afc8a452377f8a47a13d56978d763d

**Comment by lpla** [comment]
Thank you!
