### ISSUE TITLE
LEB128 in binary templates

### ISSUE THREAD

**Issue by boneskull** [HexFiend/HexFiend#232]
I'm looking at implementing a binary template ... these are pretty awesome. 

I'm wondering:

1. If you knew how to implement, specifically, ULEB128 decompression in Tcl, so it could be viewed in the template pane, or
1. If a procedure could be exposed somehow (as a "built-in") to handle this, or
1. ~~If I were to attempt to implement this myself, if you had any good resources you could point me to?  I have not used Tcl before.~~

Thank you for this excellent tool!

**Comment by boneskull** [comment]
I think this makes sense as a built-in command, but here's a naive implementation, if someone can use it.  

```tcl
proc uleb128 args {
  set result 0
  set shift 0
  set count 0
  while {true} {
    set byte [uint8]
    if {$shift == 63 && $byte != 0 && $byte != 1} {
      # this is an error
      set result 0
      break
    }
    set result [expr {$result | (($byte & -129) << $shift)}]
    incr count
    incr shift 7
    if {$byte < 128} {
      break
    }
  }
  foreach arg $args {
    entry $arg $result $count
  }
  return $result
}

# Usage

# store result; do not create entry
set value [uleb128] 

# store result & create entry
set value [uleb128 "Some Value"]

# create entry only
uleb128 "Some Value"
```

**Comment by kainjow** [comment]
Hex Fiend supports this type for the Data Inspector already: https://github.com/ridiculousfish/HexFiend/blob/master/app/sources/DataInspector.m#L524

I've been thinking of merging these data types with the Tcl controller so they could be shared. Maybe we could start with this type.

**Comment by kainjow** [comment]
I added `uleb128` and `sleb128` commands that can be used like the other type versions (with or without a label). These are based on the existing ones in the data inspector, but now they all share the same logic.
