### ISSUE TITLE
"Open Drive" broken

### ISSUE THREAD

**Issue by tajmahal2718** [HexFiend/HexFiend#257]
When I try to use the "Open Drive" command, it doesn't work, and I get two error alerts:

1:
Failed to launch and connect helper.
The operation couldn’t be completed. (CFErrorDomainLaunchd error 4.)

2:
The document “disk1s1” could not be opened. You don’t have permission.
To view or change permissions, select the item in the Finder and choose File > Get Info.

This happens no matter if I select "disk1s1 Macintosh HD" or "disk1 AppleAPFSMedia".

I hope I'm not supposed to be messing with the permissions of my startup drive in order to be able to open it in Hex Fiend.

Environment: macOS 10.14.6, SIP disabled, user is admin; MBP Early 2015

Occurs with both HexFiend 2.12 and 2.13.0b2 (both obtained via the GitHub releases page)

**Comment by kainjow** [comment]
Do you have an external drive to test with?

**Comment by tajmahal2718** [comment]
Just tried a FAT32 32 GB SanDisk USB 3.0 drive. Same error.

**Comment by kumowoon1025** [comment]
I am just wondering about the history, where did the "fortunateson" helper come from? Is it (or was it) maintained separately?

**Comment by kainjow** [comment]
> I am just wondering about the history, where did the "fortunateson" helper come from? Is it (or was it) maintained separately?

I want to say it was example code from Apple back in the day. But googling any of the keywords leads nowhere. Apple doesn't like keeping old documentation and example code, so if this was the case, seems like it's long gone.

The way this privileged helper works is through a mechanism that is not really used anymore. I've only experienced it in HF.

This component has always been tricky and based upon some not-well documented privileged escalation components that Apple really doesn't want you to use. The (out of date) App Store version of HF doesn't include it because you can't for the App Store. I have been debating removing the feature entirely. But, I'll see if I can reproduce any errors and if so look into a fix.

**Comment by kumowoon1025** [comment]
It's obviously not a perfect replacement, but have you tried using disk images? It's what I've been using to try to figure out what the heck is going on when the open drive menu item is clicked, only problem is it works a little _too_ well, at least for read-only volumes with no ownership. I think it is possible to have an image "attached" and showing up as a block device but not mounted, just can't figure out how. (OS update apps sometimes do this with the InstallESD.dmg I think.

**Comment by kainjow** [comment]
Disk images are owned by the user, so you don't need privileged escalation to access them.

**Comment by MarcusJohnson91** [comment]
Do you have System Integrity Protection enabled?

**Comment by kumowoon1025** [comment]
> Disk images are owned by the user, so you don't need privileged escalation to access them.

I don't mean read the disk image files themselves, but if you like, use sudo to mount a disk image, it kind of emulates a system owned drive.

**Comment by tajmahal2718** [comment]
> Do you have System Integrity Protection enabled?

Who, me? No, it's disabled, as stated in the issue description.

**Comment by kainjow** [comment]
> > Disk images are owned by the user, so you don't need privileged escalation to access them.
> 
> I don't mean read the disk image files themselves, but if you like, use sudo to mount a disk image, it kind of emulates a system owned drive.

Yes, that is what I'm referring to. You don't need sudo to mount a disk image nor do you need it to read the mounted disk image object.

`disk2` below is a disk image:
```
$ ls -l /dev/ | grep disk
brw-r-----  1 root     operator         1,   0 Apr 11 10:57 disk0
brw-r-----  1 root     operator         1,   1 Apr 11 10:57 disk0s1
brw-r-----  1 root     operator         1,   2 Apr 11 10:57 disk0s2
brw-r-----  1 root     operator         1,   3 Apr 11 10:57 disk1
brw-r-----  1 root     operator         1,   4 Apr 11 10:57 disk1s1
brw-r-----  1 root     operator         1,   7 Apr 11 10:57 disk1s2
brw-r-----  1 root     operator         1,   5 Apr 11 10:57 disk1s3
brw-r-----  1 root     operator         1,   8 Apr 11 10:57 disk1s4
brw-r-----  1 root     operator         1,   6 Apr 11 10:57 disk1s5
brw-------  1 kainjow  staff            1,   9 May 31 16:22 disk2
crw-r-----  1 root     operator         1,   0 Apr 11 10:57 rdisk0
crw-r-----  1 root     operator         1,   1 Apr 11 10:57 rdisk0s1
crw-r-----  1 root     operator         1,   2 Apr 11 10:57 rdisk0s2
crw-r-----  1 root     operator         1,   3 Apr 11 10:57 rdisk1
crw-r-----  1 root     operator         1,   4 Apr 11 10:57 rdisk1s1
crw-r-----  1 root     operator         1,   7 Apr 11 10:57 rdisk1s2
crw-r-----  1 root     operator         1,   5 Apr 11 10:57 rdisk1s3
crw-r-----  1 root     operator         1,   8 Apr 11 10:57 rdisk1s4
crw-r-----  1 root     operator         1,   6 Apr 11 10:57 rdisk1s5
crw-------  1 kainjow  staff            1,   9 May 31 16:22 rdisk2
```

**Comment by kainjow** [comment]
The only other report we've gotten about this not working is #140 where it sounds like SIP is disabled since the user could modify the device's permissions.

I wonder if this is the issue? @tajmahal2718 are you able to enable SIP and see if it works then?

**Comment by kumowoon1025** [comment]
> 
> You don't need sudo to mount a disk image nor do you need it to read the mounted disk image object.
> 

Of course, and I am aware of that. But you _can_ mount a disk image using `sudo hdiutil mount` and the block device for it will be owned by `root:operator` like the block devices for all physical drives are by default.

`disk0` and `disk1` are the on-board SSD and exported APFS container. `disk2` is a SATA drive, and `disk6` is a FAT thumb drive. `disk3`, `disk4` and `disk5` are all disk images, but `disk4` was mounted as root.
```
brw-r-----  1 root          operator         1,   0 May 23 12:34 disk0
brw-r-----  1 root          operator         1,   1 May 23 12:34 disk0s1
brw-r-----  1 root          operator         1,   3 May 23 12:34 disk0s2
brw-r-----  1 root          operator         1,   2 May 23 12:34 disk0s3
brw-r-----  1 root          operator         1,   4 May 23 12:34 disk1
brw-r-----  1 root          operator         1,   9 May 23 12:34 disk1s1
brw-r-----  1 root          operator         1,   8 May 23 12:34 disk1s2
brw-r-----  1 root          operator         1,   6 May 23 12:34 disk1s3
brw-r-----  1 root          operator         1,   5 May 23 12:34 disk1s4
brw-r-----  1 root          operator         1,   7 May 23 12:34 disk1s5
brw-r-----  1 root          operator         1,  10 May 23 12:34 disk2
brw-r-----  1 root          operator         1,  11 May 23 12:34 disk2s1
brw-r-----  1 root          operator         1,  12 May 23 12:34 disk2s2
br--r-----  1 kumowoon1025  staff            1,  13 May 30 14:15 disk3
brw-r-----  1 root          operator         1,  14 Jun  1 02:58 disk4
brw-r-----  1 root          operator         1,  15 Jun  1 02:58 disk4s1
brw-r-----  1 root          operator         1,  16 Jun  1 02:58 disk4s2
brw-------  1 kumowoon1025  staff            1,  17 May 25 20:53 disk5
brw-------  1 kumowoon1025  staff            1,  19 May 25 20:53 disk5s1
brw-------  1 kumowoon1025  staff            1,  18 May 25 20:53 disk5s2
brw-r-----  1 root          operator         1,  20 Jun  1 03:27 disk6
brw-r-----  1 root          operator         1,  21 Jun  1 03:27 disk6s1
```

I was suggesting it as a substitute for an external drive since for me, the problem seems to be SMJobBless not happening right for the PrivilegedHelper.

**Comment by tajmahal2718** [comment]
> I wonder if this is the issue? @tajmahal2718 are you able to enable SIP and see if it works then?

Just tried with SIP enabled. Still doesn't work. For the external drive, it's exactly the same. For the internal drive, however, I now only get the second error message ("You don't have permission."), but not the one about the helper. For the internal drive, it doesn't even attempt to install the helper application, and consequently doesn't ask for my password either.

With SIP disabled, the behaviour was identical for both the internal and external drives.

**Comment by kainjow** [comment]
I don’t think opening the internal drive is allowed, at least for a disk that is mounted or backed by a mounted disk.

**Comment by kainjow** [comment]
Thanks to @krackers thread #286 I think I found the problem. When I create a release build via the dist.sh script, I use "Developer ID Application: Kevin Wojniak" as the certificate name, and Xcode and the signing scripts find it correctly. However, it appears that is not the exact name of the certificate, and so the code requirements don't match as it's saying to do an exact match.

Here's proof:

```sh
$ echo "identifier \"com.ridiculousfish.HexFiend.PrivilegedHelper\" and certificate leaf[subject.CN] = \"Developer ID Application: Kevin Wojniak\"" | codesign -vR "-" /Volumes/Hex\ Fiend\ 2.14.1/Hex\ Fiend.app/Contents/Library/LaunchServices/com.ridiculousfish.HexFiend.PrivilegedHelper; echo $?
test-requirement: code failed to satisfy specified code requirement(s)
3
```

that fails. vs a test that uses the complete name:

```
$ echo "identifier \"com.ridiculousfish.HexFiend.PrivilegedHelper\" and certificate leaf[subject.CN] = \"Developer ID Application: Kevin Wojniak (QK92QP33YN)\"" | codesign -vR "-" /Volumes/Hex\ Fiend\ 2.14.1/Hex\ Fiend.app/Contents/Library/LaunchServices/com.ridiculousfish.HexFiend.PrivilegedHelper; echo $?
0
```

that works! 🤦 but quite embarrassing. This has probably been there since I've been distributing builds with my Developer ID.

I'll enhance the build script so it checks for a certificate with the exact name first so to not have this issue in the future.

I'll make a test build and see if that fixes it. I also gave in and bought a USB-C flash drive so I can test this feature properly in the future 🙂

**Comment by kainjow** [comment]
@krackers @tajmahal2718 can you test with 2.14.1? https://github.com/HexFiend/HexFiend/releases

**Comment by tajmahal2718** [comment]
Tested on a 2012 iMac running on 10.14.6 with SIP disabled. Working fine, thank you!

The iMac has an internal Fusion Drive. I could open both disk0 (ST32000541AS Media) and disk1 (APPLE SSD SM128E Media), and also their slices. But interestingly, it did not work for disk2 (AppleAPFSMedia), and only for some of its slices, but not for disk2s1 (Macintosh HD), which is the boot volume. So accessing the raw underlying disks works just fine, but the boot volume contained on these disks will not open …

Also, I noticed a minor usability issue with the Open Drive dialog: I could not open anything by double-clicking an entry (which works fine in regular system Open dialogs of course),  but I had to explicitly select the „Select“ button after selecting a drive to open.

**Comment by kainjow** [comment]
> Also, I noticed a minor usability issue with the Open Drive dialog: I could not open anything by double-clicking an entry (which works fine in regular system Open dialogs of course), but I had to explicitly select the „Select“ button after selecting a drive to open.

Added in cfc17cf434cb86309275a2fc5eef0ce823bc85e0
