### ISSUE TITLE
Diff view breaks up line numbers, and sometimes crashes

### ISSUE THREAD

**Issue by Siguza** [HexFiend/HexFiend#272]
Can't tell whether this is related to #270 or not, but symptoms are similar.

Create two files with 0x100 bytes each, compare them, and observe the line numbers for the second file lacking a digit/getting broken up over more than one line:

![Screenshot 2020-07-01 at 10 06 44](https://user-images.githubusercontent.com/1659374/86219947-330fba00-bb83-11ea-95b8-fe4f8e934e42.png)

Now, unlike #270 this does seem to happen with any font and not just Monaco, but interestingly it does not happen if the files are 0x110 bytes long:

![Screenshot 2020-07-01 at 10 08 23](https://user-images.githubusercontent.com/1659374/86220148-710cde00-bb83-11ea-89f6-55302a6a6d8b.png)

To top it off, I tried to test and see if this was an edge case with files having an exact size where the line after the last one would need a new digit, and in doing so, I got Hex Fiend to crash. Two crash logs are attached, here are the steps to reproduce:

1. Create two files with exactly 0x1000 bytes of content. They can be identical.
2. Open diff view (File > Compare "aaa" and "bbb").
3. Drag the window to such a width that 0x20 bytes are showing per line.
4. Close diff view.
5. Open diff view again. Now there should be 0x14 bytes per line, the left split should have line numbers in decimal, and the right one in hexadecimal.
6. Click on the line numbers in the left half to switch them to hexadecimal. Now there should be some space in front of the left line numbers, but no such space in front of the right line numbers.
7. Click on the right line numbers twice to switch them to decimal and back to hex. Now the space in front of the left line numbers should be gone.
8. Drag the window to such a width that 0x20 bytes are showing per line again.
9. Scroll to the very end of the file (make sure to scroll on the left side such as to scroll both views). Once there, you should see a cut-off line number "1000" showing, half hidden behind the diff report like so:

    ![Screenshot 2020-07-01 at 10 34 06](https://user-images.githubusercontent.com/1659374/86222417-81728800-bb86-11ea-86fe-aa2560974a7e.png)

10. Grab the vertical separator for the diff report and slide it down until the diff report is entirely hidden. That should crash Hex Fiend.

[Hex Fiend_2020-07-01-103515.crash.txt](https://github.com/ridiculousfish/HexFiend/files/4856683/Hex.Fiend_2020-07-01-103515.crash.txt)
[Hex Fiend_2020-07-01-102341.crash.txt](https://github.com/ridiculousfish/HexFiend/files/4856684/Hex.Fiend_2020-07-01-102341.crash.txt)

**Comment by kainjow** [comment]
Does the line number issue reproduce with 2.13.1?

**Comment by Siguza** [comment]
If you're referring to the release linked in #270, then yes, that's what I've been testing on. Identifies as `Version 2.13.1 (1593387597)`.

**Comment by kainjow** [comment]
I've been trying to reproduce either issue since 8eb80ad484afc8a452377f8a47a13d56978d763d was added but can't. Let me know after once a 2.18 beta gets posted if you can reproduce.
