### ISSUE TITLE
Feature Request: Automatically reload binary template

### ISSUE THREAD

**Issue by rinsuki** [HexFiend/HexFiend#291]
I'm using Binary Templates for analyze unknown binary format.

in this use case, the binary templates need to be edited frequently and reloading many times.

for this reason, I think it would be useful to have a feature that automatically reloads the binary template when it is changed.

**Comment by wader** [comment]
I've used a combination of modd and apple script as a workaround, see https://gist.github.com/wader/be983fa10ef24fa4dcb3e1a616e725dd

**Comment by kainjow** [comment]
yeah I've wanted to do this forever. Should be fairly straightforward.

**Comment by kainjow** [comment]
Related: 331
