### ISSUE TITLE
Consider changing the Xcode project format

### ISSUE THREAD

**Issue by anthroid** [HexFiend/HexFiend#301]
Consider changing the Xcode project format to allow building on other macOS versions.
Right now the project cannot be opened on Mojave 10.14.6 with Xcode 11.3.1:

<img width="532" alt="HexField_Xcode_format_Mojave" src="https://user-images.githubusercontent.com/352426/104117921-94f76c00-52ea-11eb-97b0-aa67d3517399.png">

**Comment by gingerbeardman** [comment]
You can edit it yourself FWIW

https://github.com/HexFiend/HexFiend/blob/eed63c9f9ac31fd160c5f860d063cd7a8eae99fe/HexFiend_2.xcodeproj/project.pbxproj#L6

change 53 to 50

**Comment by anthroid** [comment]
> You can edit it yourself FWIW
> 
> https://github.com/HexFiend/HexFiend/blob/eed63c9f9ac31fd160c5f860d063cd7a8eae99fe/HexFiend_2.xcodeproj/project.pbxproj#L6
> 
> change 53 to 50

Thanks, that did it for now (changing to 52 for Xcode 11.3).

**Comment by gingerbeardman** [comment]
Interesting, I took the value 50 from a new blank project I created with Xcode 11.3.1

**Comment by anthroid** [comment]
Yeah, I checked and saw the same thing. New projects in Xcode 11.3 still default to 50 (9.3 format) for some reason.

**Comment by kainjow** [comment]
I think manually setting the Xcode project version is a good workaround.
