### ISSUE TITLE
Local Privilege Escalation vulnerability

### ISSUE THREAD

**Issue by r3ggi** [HexFiend/HexFiend#303]
The `SMPrivilegedExecutables` doesn't specify if the helper has be signed with a trusted certificate. An attacker may alter the helper and make HexFiend to install it as root.

https://github.com/HexFiend/HexFiend/blob/eed63c9f9ac31fd160c5f860d063cd7a8eae99fe/app/Info.plist#L92

The code requirement should contain the following prefix: `anchor apple generic`

There was a similar case in Docker. You can read more about it on my blog - https://wojciechregula.blog/post/when-vulnerable-library-is-actually-your-physical-book/

**Comment by kainjow** [comment]
Thanks!
