### ISSUE TITLE
Comparison window layout bugs, not terribly usable.

### ISSUE THREAD

**Issue by JonathanDotCel** [HexFiend/HexFiend#305]
- attempting to change byte grouping changes only one panel's grouping
- 2nd panel starts halfway down the page
- resizing the window doesn't resize the second panel
- neither is 16 column by default

Running Catalina 10.15.7

Thanks,
J

![Screenshot 2021-01-28 at 18 51 56](https://user-images.githubusercontent.com/61208676/106184985-2c3d3a00-619a-11eb-9a62-5827d77b83ab.png)

**Comment by gparker42** [comment]
Several of these problems appear to be fixed as of version 2.16. Changing the byte grouping still misbehaves: it only changes one pane, and it resizes the window to a bad size.

**Comment by kainjow** [comment]
Byte grouping was fixed in 8eb80ad484afc8a452377f8a47a13d56978d763d
