### ISSUE TITLE
Possibility to change color of selected data

### ISSUE THREAD

**Issue by PLSomebody** [HexFiend/HexFiend#309]
Now selected data is marked with grey in hex and blue in text. In dark system theme it is almost invisible. There should be possibility to select color which will be used for marking selected data.

Widely, possibility to customize color theme in HexFiend for light and dark modes will be great.

**Comment by kainjow** [comment]
hm I think HF is using system theme colors here. I'm not in favor of customizing all colors because dark/light mode colors are part of AppKit and AppKit controls cannot be customized at this level.

I checked briefly and it looks like it matches what TextEdit is doing. can you provide screenshots so we're on the same page?

**Comment by blipmusic** [comment]
Here's a late example. The focus view the selection was made in is fine (blue), but the corresponding selection in the "passive" view has too little contrast (dark gray). For single byte values it's almost impossible to spot. The left hex view is particularly difficult in this regard. I'd personally be fine with just making both e.g. blue or whatever the most contrasting option for the current system setting is.

![hexfiend_dji1](https://user-images.githubusercontent.com/1898807/130639641-bda25954-b29d-40cd-a4b3-3c7482491de8.png)
![hexfiend_dji2](https://user-images.githubusercontent.com/1898807/130639653-90c592b9-5670-4cce-b30c-3d657ac35569.png)

**Comment by kainjow** [comment]
I added a preference "Match inactive text selection color with active" which uses the active text selection color for the text views.
Example:
<img width="525" alt="image" src="https://github.com/HexFiend/HexFiend/assets/271035/a9c18128-b635-46fb-84a5-19c4a1da1743">
