### ISSUE TITLE
When comparing, there is no source text in the "Plain Text" display

### ISSUE THREAD

**Issue by Drovosek01** [HexFiend/HexFiend#312]
When I compare 2 files and turn on "Plain Text" in the Views tab, only the text of the second file is displayed.

I need to see the text of both files, or at least the original text when editing the modified one.

![image](https://user-images.githubusercontent.com/29478700/110178517-9ee3aa00-7e17-11eb-9fba-2098a3f74c5a.png)

**Comment by kainjow** [comment]
Should be fixed for 2.18 as of 8eb80ad484afc8a452377f8a47a13d56978d763d
