### ISSUE TITLE
The document “disk2” could not be saved.  when using "OPEN DRIVE"

### ISSUE THREAD

**Issue by windirt** [HexFiend/HexFiend#315]
OS: macOS Big Sur 11.2.3
HexFiend: 2.14.1

Step: 

1. Choose OPEN DRIVE from the File menu
2. Choose disk2,  it is the mounted SD card, I want to edit the data after partition table, so I choose physical disk.
3. Asked for password twice, entered.
4. Toggle the mode to OVERWRITE
5. Modify the data on SD card.
6. "The document “disk2” could not be saved" displayed when I choose SAVE in File menu.

The SD card does not have write protected.

**Comment by kainjow** [comment]
I don't think macOS will let you open a mounted disk. Does it work if you unmount the volume in Disk Utility?

**Comment by windirt** [comment]
> I don't think macOS will let you open a mounted disk. Does it work if you unmount the volume in Disk Utility?

Thanks for the tips.  HexFiend was indeed able to save disk changes when I unmounted the SD card from the Disk Utility.
