### ISSUE TITLE
Support for 3, 5 and 7 byte integers

### ISSUE THREAD

**Issue by y8** [HexFiend/HexFiend#316]
_Current behavior_: when odd number of bytes are selected, Data Inspector  shows "(select a power of 2 bytes)" for Signed/Unsigned Int types.
_Desired behavior_: Data Inspector show integer representation of selected bytes.

It would be useful to have support for 24, 40 and 56 bit integers. I'm working with BLE advertising data and some vendors are using odd sized integers to encode data. 

Thanks!

**Comment by kainjow** [comment]
Implemented in #355 thanks to @fosterbrereton
