### ISSUE TITLE
"Template" pane never shrinks down

### ISSUE THREAD

**Issue by ershov** [HexFiend/HexFiend#322]
"Template" pane never shrinks down, thus making the window so wide that it's impossible to use the app.

Steps to reproduce:

1. Open a file.
2. Open "Templates" pane.
3. Go out of full screen.

Expected result: The proportion of the hex view and template go back to reasonable.

Actual outcome: Template pane width stays the same; hex view shrinks down to the minimal size (1 byte per row). Resizing the window only changes the width of hex view but it's impossible to resize the templates width.

---

I must say, resizing behaves weirdly in this app.
Sometimes it's impossible to resize the width - only height.
There's on splitter or anything allowing to adjust the ratio between hex view and templates.

The worst thing about this bug is that once the width is screwed, there's no easy way to fix it.
Re-installing the app doesn't help.

I was able to work-around this thing:

1. Convert app's prefs to text format:\
`$ plutil -convert xml1 -o /tmp/q ~/Library/Preferences/com.ridiculousfish.HexFiend.plist`
2. Edit /tmp/q and fix `BinaryTemplateRepresenterWidth` to a sane value like 300 or 500
3. Convert prefs back to binary:\
`$ plutil -convert binary1 -o ~/Library/Preferences/com.ridiculousfish.HexFiend.plist /tmp/q`

Unfortunately, I'm 100% sure an average user will never be able to fix it. I couldn't google the solution too.

**Comment by kainjow** [comment]
In 2.14 you can resize it now. It’s documented in the release notes and the “welcome” popover:

> The binary templates view can be resized by holding down the Command key when resizing the window. The manual size field in Preferences has been removed

https://hexfiend.github.io/HexFiend/ReleaseNotes.html

**Comment by ershov** [comment]
Can you make the information more visible when user tries to resize the window?
