### ISSUE TITLE
File compare mode selection

### ISSUE THREAD

**Issue by marcoburato** [HexFiend/HexFiend#323]
The current file comparison algorithm doesn't seem to scale well. For instance, comparing two 4MB files would just take forever.

It would be nice to have a simpler comparison mode which, instead of trying to find insertions and removals, just compares files byte-per-byte and reports the different ranges by grouping adjacent different bytes.

The comparison mode could be configured from the app Preferences window.

**Comment by GeckoGB** [comment]
Yes, currrent comparison very often detects incorrect insertions/removal and so desynchronizes comparison between 2 files when only some bytes are modified in fixed offsets. A "dumb" byte to byte comparison would be very welcome, and probably much faster!

**Comment by kainjow** [comment]
Going to close in favor of https://github.com/HexFiend/HexFiend/issues/346
