### ISSUE TITLE
Feature Request: A way to halt Template evaluation and show what's been processed already

### ISSUE THREAD

**Issue by fosterbrereton** [HexFiend/HexFiend#328]
While working on a template it's common to hit a case that causes an error (or even crashes HF) because the template is incomplete. It would be useful to have an instruction (`abort`, say) that halts further evaluation of the template file and dumps whatever entries have already been produced to the view. I tried `exit`, but that quit HF entirely.

**Comment by wader** [comment]
Hi, i’ve collected a few tricks while writing templates here https://gist.github.com/wader/be983fa10ef24fa4dcb3e1a616e725dd

**Comment by fosterbrereton** [comment]
Fantastic - thanks!

**Comment by wader** [comment]
Mine too 😬😊 example modd.conf is for https://github.com/cortesi/modd but the osascript should be quite easy to use with other change notifiers also

**Comment by kainjow** [comment]
@fosterbrereton does that work for you? If so, you can close this thread.

**Comment by wader** [comment]
@kainjow yes can do, on vacation atm so in week or so. Feel free to add it before that if you want @fosterbrereton or @kainjow

**Comment by fosterbrereton** [comment]
@kainjow one feature I would like to see added is some kind of `sentry` capability. When I'm analyzing binary files, more often than not I'm investigating corrupted files, trying to figure out where things went off the rails. In such cases, it is helpful to set up guardrails within the template itself, to notify the user when the internal structure of the file is not consistent (for a recent example of this, see [here](https://github.com/HexFiend/HexFiend/blob/ef4570e2e0afee624d26c7f4a2dc7d2ab6941dcd/templates/Archives/ZIP.tcl#L75). ZIP files generated by macOS have several internal inconsistencies, unfortunately.)

One of the most common ways to do this is to set up a read sentry. In file formats (or sub-sections within a format) where the length of the upcoming subsection is known, a sentry can be established. The sentry will assert that if subsequent reads do not match the sentry length, template interpretation can be halted and an error shown.

For example, in the PNG file format, each [chunk's length is specified within the file](https://github.com/HexFiend/HexFiend/blob/ef4570e2e0afee624d26c7f4a2dc7d2ab6941dcd/templates/Images/PNG.tcl#L9). If a sentry were placed around the chunk, it would assert the internal structure of that chunk is well-formed. Something like:

```tcl
section "Chunk $chunk_type" {
    set length [uint32 "Length"]
    ascii 4 "Type"
    # Establish the sentry. In PNG, the length counts _only_ the chunk's data.
    sentry $length {
        if {$chunk_type == "IHDR"} {
            uint32 "Width"
            uint32 "Height"
            uint8 "Bit Depth"
            uint8 "Color Type"
            uint8 "Compression Method"
            uint8 "Filter Method"
            uint8 "Interlace Method"
        } else {
            move $chunk_len
        }
    } # end of sentry. EXACTLY $length bytes must have been read by the close of the sentry.
    hex 4 "CRC"
}
```

Note that by requiring the read count be exactly the sentry length, it catches cases where the length value itself has become corrupted.

**Comment by fosterbrereton** [comment]
I was able to build such a command, and have it as part of PR #333. I'll close this request out. Thanks for the discussion and the tips!

**Comment by fosterbrereton** [comment]
@wader I added your `catch` trick [as a proc](https://github.com/HexFiend/HexFiend/pull/333/commits/99e428c422d49da06e0e4c700d34a5b40278e48a#diff-861331ce7cea5838231cfcfe987b463234b12a45f61c4930412f733f7edd99e6R106-R125) to PR #333, which hopefully clarifies its intent and readability within template files. If you can suggest a way to improve it please let me know.

**Comment by wader** [comment]
@fosterbrereton Nice, good idea i think. How does the error info string look like when added as an entry value? cramped?

**Comment by fosterbrereton** [comment]
@wader only the first line of the error report is visible in the tree. You can copy-paste the entire error from there, though, into the editor of your choice, and it will give you the whole thing. In my experience that's an acceptable tradeoff when you can have both the entries up to the point of the error and the error itself in a single view.

**Comment by wader** [comment]
@fosterbrereton hey! not sure how to contact you so hope thru a hexfiend issue is ok! i've stumbled upon your https://github.com/binspector/binspector tool some weeks ago so i thought you might be interested in a tool i've been working on for the last year https://github.com/wader/fq, it's heavily inspired by hexfiend and spookley similar to binspector in some ways :)

**Comment by fosterbrereton** [comment]
@wader hey- thanks for reaching out! If you need to, you can reach me at my Adobe address (fbrereto). I’m always interested in binary format analysis tools so will be sure to check out yours. Thanks for the recommendation.

**Comment by wader** [comment]
@fosterbrereton No problem and good to know! as your working on a similar tool i assumed we might have faced similar challenges dealing with various binary files. In my case debugging broken media files, write muxers/codecs, educational and all kinds of aggregations and queries. Happy holidays!
