### ISSUE TITLE
zip template and zip archive created with macOS Archive Utility

### ISSUE THREAD

**Issue by grylem** [HexFiend/HexFiend#343]
Hi
Zip template does not work for archive created with Archive Utility and some others.
Thanks.

**Comment by lemnet** [comment]
I confirm that the template is not working...
I'll take a look at this today or in the next few days

**Comment by lemnet** [comment]
That was easy... Empty files were not taken into account

**Comment by fosterbrereton** [comment]
@kainjow Does your PR close this issue?
