### ISSUE TITLE
Clarify versions in template reference

### ISSUE THREAD

**Issue by panda-byte** [HexFiend/HexFiend#345]
The template reference would benefit from checking availability of commands / options by version. For example, the `-collapsed` option and `sectioncollapse` command are not available in the current release 2.14.1, but this is not stated in the reference.

**Comment by fosterbrereton** [comment]
Hopefully this can be addressed via #353

**Comment by kainjow** [comment]
Updated in https://github.com/HexFiend/HexFiend/commit/445bfc1141f1ce507656c41340568d2430d89a06
