### ISSUE TITLE
Color Bytes: flashing window contents when scrolling

### ISSUE THREAD

**Issue by gingerbeardman** [HexFiend/HexFiend#347]
Any idea why this strange flashing of the layout is happening when I scroll?

## Analysis
- It happens in both dark mode and normal mode
- It only happens when Font > Color Bytes is checked

## Setup
- Version 2.14.1 (1615771335)
- MacOS 11.6 (20G165)
- Mac mini with Intel UHD Graphics 630 1536 MB

https://user-images.githubusercontent.com/49612/140189230-ba61990c-6fe5-43cb-bd25-8cab4bb9dd89.mov

**Comment by kainjow** [comment]
Odd. Looks like an OS or driver bug, unless HF is doing something on a thread that it shouldn’t be.

**Comment by kainjow** [comment]
Are you able to update to Monterery and see if it reproduces there?

**Comment by gingerbeardman** [comment]
Updating to Monterey and iOS 15 are on my radar, hopefully soon.

**Comment by kainjow** [comment]
@gingerbeardman are you still seeing this? wonder if it's a hardware issue.

**Comment by gingerbeardman** [comment]
I can no longer repro on Monterey 12.4 (21F79) on the same Intel Mac Mini and Hex Fiend versions.

Thanks for checking in!
