### ISSUE TITLE
Ability to favourite an encoding to add it to the top level Text Encoding menu items

### ISSUE THREAD

**Issue by gingerbeardman** [HexFiend/HexFiend#349]
The ability to favourite an encoding to add it to the top level Text Encoding many would be a real timesaver.

I am assuming promoting an encoding to the top level menu would enable it to be set as default.

Currently I am using solely MacJapanese on all files and whilst MacJapanese is selected as default encoding it is hidden off screen, so it's a hassle to gt back to it, and even more difficult if it's already highlighted (See #350).

<img width="223" alt="Screen shot 2021-11-04 at 11 44 05" src="https://user-images.githubusercontent.com/49612/140308383-a930bc4c-561a-4c16-aa22-5049841e340f.png">

<img width="326" alt="Screen shot 2021-11-04 at 11 44 13" src="https://user-images.githubusercontent.com/49612/140308389-50e1c248-219f-4ce6-867b-57bf582c367f.png">

**Comment by kainjow** [comment]
I’ve started on this a little but wanted to get your input on how it might work. Initially I was thinking of just adding a checkbox column to the existing table in the Choose Encodings window but that doesn’t allow you to reorder them in the menu easily. You’d have to uncheck them and recheck them in order. The other idea is to have the window show the list of encodings that are in the menu and let you drag and drop reorder them, along with a way to add and remove them. Then the existing table of encodings would become the source list from where encodings are added to the menu list.

**Comment by gingerbeardman** [comment]
Would alphabetical ordering in the menu not make most sense? Then the simple checkbox approach would work.

I would add Japanese encodings in there, probably as a one time thing.

**Comment by kainjow** [comment]
Yes that would be straightforward. Thanks.
