### ISSUE TITLE
Default string "-[HFStatusBarRepresenter createView]" remains in status bar until first user interaction

### ISSUE THREAD

**Issue by sh95014** [HexFiend/HexFiend#358]
Hi! I'm incorporating HexFiend.framework in an [Apple //e emulator](https://github.com/sh95014/AppleWin) (a port of AppleWin to macOS, to be precise) to display the contents of a file on a floppy disk image, and it's working pretty great. One issue I've encountered is that the status bar initially shows `-[HFStatusBarRepresenter createView]` before the user interacts with the view:

<img width="467" alt="Screen Shot 2022-02-11 at 5 20 05 PM" src="https://user-images.githubusercontent.com/95387068/153690805-a8dd9a63-231a-4889-9cba-60537a517467.png">

I see code that does this deliberately in `HFStatusBarRepresenter.m`:
```
    _statusView.stringValue = [NSString stringWithUTF8String:__FUNCTION__]; // dummy
```
but what is your expectation in terms of who or what event is supposed to clear it?

Thanks!

**Comment by kainjow** [comment]
In Hex Fiend the representer has controllerDidChange called with -1 to signal a default setup from addRepresenter. How are you setting up the representer?

**Comment by sh95014** [comment]
I mainly just adapted the code from HexFiendling:
```
        self.hfController = [[HFController alloc] init];
        HFSharedMemoryByteSlice *byteSlice = [[HFSharedMemoryByteSlice alloc] initWithUnsharedData:data];
        HFByteArray *byteArray = [[HFBTreeByteArray alloc] init];
        [byteArray insertByteSlice:byteSlice inRange:HFRangeMake(0, 0)];
        [self.hfController setByteArray:byteArray];
        
        HFLayoutRepresenter *layoutRep = [[HFLayoutRepresenter alloc] init];
        HFLineCountingRepresenter *lcRep = [[HFLineCountingRepresenter alloc] init];
        HFHexTextRepresenter *hexRep = [[HFHexTextRepresenter alloc] init];
        HFStringEncodingTextRepresenter *asciiRep = [[HFStringEncodingTextRepresenter alloc] init];
        HFVerticalScrollerRepresenter *scrollRep = [[HFVerticalScrollerRepresenter alloc] init];
        HFStatusBarRepresenter *statusRep = [[HFStatusBarRepresenter alloc] init];
        
        [self.hfController addRepresenter:layoutRep];
        [self.hfController addRepresenter:lcRep];
        [self.hfController addRepresenter:hexRep];
        [self.hfController addRepresenter:asciiRep];
        [self.hfController addRepresenter:scrollRep];
        [self.hfController addRepresenter:statusRep];

        [layoutRep addRepresenter:lcRep];
        [layoutRep addRepresenter:hexRep];
        [layoutRep addRepresenter:asciiRep];
        [layoutRep addRepresenter:scrollRep];
        [layoutRep addRepresenter:statusRep];
        
        // shrink the window to exactly fit desired bytes per row
        CGRect frame = self.filePreviewPanel.frame;
        frame.size.width = [layoutRep minimumViewWidthForBytesPerLine:16];
        [self.filePreviewPanel setFrame:frame display:NO];
        layoutView = [layoutRep view];
```
But I dug into it a bit more, and the problem seems to be that `updateString` (which does set the status string to empty) is called by `controllerDidChange` and `addRepresenter` _before_ `createView` is implicitly called by `_updateBytesPerLine` when one of the other representers is being added to the `HFLayoutRepresenter`.

Hopefully the code snippet above makes it obvious to you what I'm doing wrong.

**Comment by sh95014** [comment]
Swapping the additions to `hfController` and `layoutRep` above doesn't work because various bits of code in `HFController` (`bytesPerColumn` in my case) assert that it must already have a controller.
