### ISSUE TITLE
Compare is slow 🐢

### ISSUE THREAD

**Issue by greggman** [HexFiend/HexFiend#360]
Please don't take this as a complaint, more as a maybe TODO for some volunteer, maybe even me if I can find the time.

I tried to compare two 1gig files. Short story long, I copied an .MP4 from my Mac to a network hard drive and it's not playable there (vs 100s of others that are). I thought maybe the hard drive was going bad so I bought a new one. Tried copying the same file to the new one, same problem. Somehow the file is not making it verbatim to the network drive. So, I tried copying the file back to the local drive (so I have two 1gig local files). I opened both in HexFiend, picked compare, it's been 3 hours and the compare process bar is at around 40% (so apparently about 5 hours to go)

It sounds like there might be some low-hanging optimization there.

**Comment by greggman** [comment]
Well, I let it run for 10hrs. It process bar got to 100% 2 hours ago and then it just sat there and use 900% CPU according to activity monitor (wasn't using lots of memory thankfully). Unfortunately with no idea if it would ever finish and the fact that my entire M1 Max MBP was running at 5fps I end up killing it :P   I suppose I should build it and run the profiler on it.

**Comment by jmkd3v** [comment]
I am also encountering this - I simply can't diff these two files, it reaches 100% fairly quickly and then just ever completes.

**Comment by WWWFWWW** [comment]
Compare function bogs down even with 22 MB files, to the point of completely stalling around 90%, even with both files very similar bytewise. Not sure what's going on there. Apple silicon, FIY.

**Comment by MarcusJohnson91** [comment]
> Compare function bogs down even with 22 MB files, to the point of completely stalling around 90%, even with both files very similar bytewise. Not sure what's going on there. Apple silicon, FIY.
> 
> edit: Not that similar, apparently – sorry. Still, cmp -x only takes a few seconds, even if the resulting diff file is rather large.

Nope, HexFiend did this on Intel too even when comparing JPEGs that are only a couple megabytes.

there’s some combinatorial explosion that makes it a never ending loop.

the algorithm needs a window, say 1KiB to compare at a time, and walk through the file step by step through that window.
