### ISSUE TITLE
Operation for Sum

### ISSUE THREAD

**Issue by Gliou** [HexFiend/HexFiend#362]
Is it possible to add a command for operation ?
Ex: Add all bit, byte, word, long word for do a checksum for example ? Add a selection ?

**Comment by kainjow** [comment]
Templates might help. You could check to see if Tcl supports the checksum you want to use.

**Comment by SeanMcLoughlin** [comment]
Some basic operations being present in the GUI would be a very welcome addition. Some things I think would be good:
- Shifting operations (left/right, circular left/right)
- Invert endianness
- Add/Sub/Mult/Div/And/Or/Xor all bytes
- And/Or/Xor bytes from one file with bytes from another

**Comment by kainjow** [comment]
Going to dupe this against #194. I'm going to use that for this general feature of performing an operation on bytes.
