### ISSUE TITLE
Only the top section of nested collapsed sections is collapsed on template load

### ISSUE THREAD

**Issue by LogicalJoe** [HexFiend/HexFiend#364]
```
section -collapsed "section"
entry data ""
section -collapsed "section"
entry data ""
endsection
endsection
```
only collapses the top `section`

https://user-images.githubusercontent.com/47825483/168114409-0a8fee93-696a-4eeb-80c5-2fd41e8dc5a1.mov

**Comment by kainjow** [comment]
@ahelsley maybe you could take a look?

**Comment by kainjow** [comment]
nvm, I made the fix. 

Thanks for the report @LogicalJoe!
