### ISSUE TITLE
Big Sur Icon

### ISSUE THREAD

**Issue by dapetcu21** [HexFiend/HexFiend#367]
Hi! I think it would be nice if the icon gets updated for the new Big Sur icon guidelines, so that it looks good alongside all the other square-ish icons in the dock.

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

Here's a couple community-made icons: https://macosicons.com/#/hex%20fiend

Seems like one of those is made by @tomt000, whom I found on Twitter and Github:
https://twitter.com/tomt000
https://github.com/tomt000

If you don't have the resources to redesign the app icon, it might be worth asking them if they'd be willing to give their permission for their icon to be used as the official app icon.

**Comment by kainjow** [comment]
This was added in 2.14.1. If you're on the App Store version it is out of date.
