### ISSUE TITLE
'Jump to Offset' highlighting misaligned

### ISSUE THREAD

**Issue by lafinsd** [HexFiend/HexFiend#368]
macOS Monterey 12.3.1 HexFiend 2.14.1 MacBook Air (Intel)

1. The misalignment seems to interact with the byte grouping in force at the time of the jump. The highlighting does in fact appear to always include the target but is inconsistent in its extent.
2. The highlighting flashes but its duration is too short. It should stay on longer or even persist.

Inappropriate, but I love this app, in particular the Binary Template feature for my current use. Awesome.

**Comment by kainjow** [comment]
Indeed it does seem dependent on the byte grouping in some odd way. What byte grouping are you using btw? I guess we need to define what it should be. Maybe the length it uses for 4 bytes would be good, since that's default.

**Comment by lafinsd** [comment]
I typically use the 4 byte grouping even though it is unrelated to the data I am looking at. 

The chosen byte grouping appears to be controlling when the highlighting appears: 4 byte grouping generates a 4 byte width highlight, 2 byte grouping a 2 byte width, 16 generates 16, etc. It's just the left alignment that seems to be off. 

As for what it should be, good question. A width of 4 seems reasonable though you have to deal with the boundary condition on the right side. I suppose an argument could be made for a width of a single byte. A single byte is the granularity of the jump target specification. There's no a priori relationship between the byte grouping and how the target address aligns with that grouping. 

I still think the highlighting needs to be visible longer or even persist.
