### ISSUE TITLE
Add option to make text search function case insensitive

### ISSUE THREAD

**Issue by dill0n5** [HexFiend/HexFiend#370]
Currently search function is case sensitive. It would be very helpful to have an option to set the search function to be case insensitive.

**Comment by kainjow** [comment]
See https://github.com/HexFiend/HexFiend/issues/109 for some history

**Comment by dill0n5** [comment]
Yes, that thread discusses the issue, but doesn't provide a resolution. The thread also hasn't been updated in 4 years, so I figured I'd open a new issue and hope for some renewed attention to the request.

**Comment by kainjow** [comment]
There is a naive implementation in the code but there's no GUI to enable it yet: https://github.com/HexFiend/HexFiend/issues/109#issuecomment-401583243

**Comment by kainjow** [comment]
Will use https://github.com/HexFiend/HexFiend/issues/376 for updates.
