### ISSUE TITLE
Switching endianness for UInt has no effect

### ISSUE THREAD

**Issue by VaslD** [HexFiend/HexFiend#371]
### Steps to Reproduce Issue:

- Open binary with HexFiend in read-only mode.
- Select a 2-byte sequence.
- Switch inspector to Unsigned Integer, and toggle between LE and BE.
- Observe changes in the number to the right.

### Issue

Decoded numeric value does not change. It stays LE-decoded in both decimal or hex format.

### Expected Behavior

Values are decoded according to LE and BE settings.

### Screenshots

<img width="317" alt="Screenshot 06-07 17 35 54@2x" src="https://user-images.githubusercontent.com/3415065/172348255-1781e499-be9e-42ff-ad0f-bec1eafb99b8.png">

<img width="317" alt="Screenshot 06-07 17 36 48@2x" src="https://user-images.githubusercontent.com/3415065/172348406-57dd56ac-9426-493a-9acd-08077af33923.png">

**Comment by kainjow** [comment]
Looks like a regression from 39ff4638a2c11bafbc53056dfa89ac3d1d7d88cc

**Comment by fosterbrereton** [comment]
Thank you for fixing this one!
