### ISSUE TITLE
Included default template files not found (wrong search path)

### ISSUE THREAD

**Issue by GeckoGB** [HexFiend/HexFiend#375]
Some templates, like JPEG or PNG for example, include other default templates, like:
include "Metadata/Exif.tcl"
include "Utility/General.tcl"

But these includes fail with an "_Include file not found_" error because they are searched in "~/Library/Application Support/com.ridiculousfish.HexFiend/Templates" instead of inside Hexfiend application package "/Applications/HexFiend/Contents/Resources/templates/".

HexFiend v. 2.16 (1655090551) MacOS 10.15.7.

**Comment by kainjow** [comment]
Thanks for the report!
