### ISSUE TITLE
`endsection;sectioncollapse` leaks memory

### ISSUE THREAD

**Issue by LogicalJoe** [HexFiend/HexFiend#377]
Was debugging a template that uses `endsection` and `sectioncollapse` conditionally within loops that wasn't returning an error or even updating in the viewer on refresh and this seemed to be the underlying issue.
```
endsection
sectioncollapse
```
This also seems to cause other problems and will leak farther if other things are done while it attempts to [re]load the template.
<img width="927" alt="Screen Shot 2022-07-01 at 035334" src="https://user-images.githubusercontent.com/47825483/176850482-425e2053-74e7-4db6-8b27-e1ef2acef839.png">
`Leak: 0x600000e28980  size=32  zone: DefaultMallocZone_0x102710000   NSDictionary  ObjC  CoreFoundation`

Edit: tested and still have the issue on the latest version (c490934).

**Comment by kainjow** [comment]
looks like some error handling is needed for validating a section exists when these commands are used.
