### ISSUE TITLE
Please add Japanese International for can read kanji text

### ISSUE THREAD

**Issue by enma09art** [HexFiend/HexFiend#381]
Many japanese games are in kana-kanji, and hex fiend cannot read this text, please add this feature. 010 editor and HxD had this and is very useful for fan translations.
![A6BED942-74C3-4ED0-846B-B2B2A292C4F7](https://user-images.githubusercontent.com/87793814/184463659-21807943-4b83-4fd0-910c-dd925b1d5247.jpeg)

**Comment by kainjow** [comment]
Does ShiftJIS encoding cover this?

**Comment by kainjow** [comment]
I haven't found a lot to go on this subject. Although this seems interesting https://github.com/00StevenG/NSString-Japanese 

HF has custom encoding support which could help. See #95
