### ISSUE TITLE
Open Drive does not work

### ISSUE THREAD

**Issue by carlosperate** [HexFiend/HexFiend#389]
Trying to view a disk doesn't seem to work again, similarly to:
- https://github.com/HexFiend/HexFiend/issues/257

Tried this with macOS 13 Ventura with SIP disabled and in macOS 12 Monterey with SIP enabled, both x86 Macbooks. With Hex Fiend v2.16.0 and v2.14.1. I also tried launching the app with and without sudo (`sudo open /Applications/Hex\ Fiend.app/`)

In both cases I was connecting a USB MSD device and trying to view it.

It asks for my password twice:
a) First to "install a new helper"
b) Then to "make changes"
This happens every time I try to do this on a fresh run of the app. So if I open the app and try to view the drive it will do this and fail, but any subsequent attemp will fail directly. If I close the app, open it, and try again it will ask for my password again:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/4189262/198700591-f661a0df-00f4-49f0-afcc-6f72a1e8ab5b.png" width="49%"> <img width="370" alt="image" src="https://user-images.githubusercontent.com/4189262/198701195-dfdc9344-3814-4d70-a846-5f04daa2687d.png" width="49%">

And after asking for the password, it then fails to open the drive with this error:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/4189262/198700043-589c44fb-4f46-40e4-94b7-37c30c4793c9.png">

Btw, I absolutely love this app, thanks for making it!

**Comment by carlosperate** [comment]
Actually, running `sudo chmod 666 /dev/disk2*` in the Monterey x86 Macbook with SIP enabled has somewhat worked, as indicated in:
- https://github.com/HexFiend/HexFiend/issues/140#issuecomment-407177717

I get this pop up:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/4189262/198702724-2af00a71-241f-4d95-a2df-9228fb6ccd29.png">

And after accepting it it shows me the MVR stuff, but all zeros after that?
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/4189262/198702936-c8409661-b5d4-4c4b-8cdc-da7a7434b141.png">

If I unmount the device and try to open the disk it doesn't show the pop up about the rdisk anymore, but the result is the same. Is that normal? This is a FAT16 drive and I was hoping to see the FAT/DATA clusters data as well.

**Comment by carlosperate** [comment]
The output of `ls -al /dev/ | grep disk` as requested in https://github.com/HexFiend/HexFiend/issues/140#issuecomment-450469718:

```
ls -al /dev/ | grep disk
brw-r-----   1 root             operator        0x1000000 29 Sep 13:31 disk0
brw-r-----   1 root             operator        0x1000002 29 Sep 13:31 disk0s1
brw-r-----   1 root             operator        0x1000003 29 Sep 13:31 disk0s2
brw-r-----   1 root             operator        0x1000001 29 Sep 13:31 disk0s3
brw-r-----   1 root             operator        0x1000004 29 Sep 13:31 disk1
brw-r-----   1 root             operator        0x1000006 29 Sep 13:31 disk1s1
br--r-----   1 root             operator        0x100000b 29 Sep 13:31 disk1s1s1
brw-r-----   1 root             operator        0x1000007 29 Sep 13:31 disk1s2
brw-r-----   1 root             operator        0x1000005 29 Sep 13:31 disk1s3
brw-r-----   1 root             operator        0x100000a 29 Sep 13:31 disk1s4
brw-r-----   1 root             operator        0x1000009 29 Sep 13:31 disk1s5
brw-r-----   1 root             operator        0x1000008 29 Sep 13:31 disk1s6
brw-rw-rw-   1 root             operator        0x100000c 28 Oct 18:10 disk2
crw-r-----   1 root             operator        0x1000000 29 Sep 13:31 rdisk0
crw-r-----   1 root             operator        0x1000002 29 Sep 13:31 rdisk0s1
crw-r-----   1 root             operator        0x1000003 29 Sep 13:31 rdisk0s2
crw-r-----   1 root             operator        0x1000001 29 Sep 13:31 rdisk0s3
crw-r-----   1 root             operator        0x1000004 29 Sep 13:31 rdisk1
crw-r-----   1 root             operator        0x1000006 29 Sep 13:31 rdisk1s1
cr--r-----   1 root             operator        0x100000b 29 Sep 13:31 rdisk1s1s1
crw-r-----   1 root             operator        0x1000007 29 Sep 13:31 rdisk1s2
crw-r-----   1 root             operator        0x1000005 29 Sep 13:31 rdisk1s3
crw-r-----   1 root             operator        0x100000a 29 Sep 13:31 rdisk1s4
crw-r-----   1 root             operator        0x1000009 29 Sep 13:31 rdisk1s5
crw-r-----   1 root             operator        0x1000008 29 Sep 13:31 rdisk1s6
crw-r-----   1 root             operator        0x100000c 28 Oct 18:10 rdisk2
```

**Comment by kainjow** [comment]
@carlosperate any update? haven't heard from anyone else on this issue, so I suspect it's something on your machine.
