### ISSUE TITLE
Shift JIS texts are displayed incorrectly

### ISSUE THREAD

**Issue by sdsnatcher** [HexFiend/HexFiend#394]
When opening files with the Japanese Shift JIS encoding, they're displayed incorrectly, even after this encoding is selected.

macOS TextEdit shows them just fine when requested to open the file with Shift JIS encoding.

The attached screenshots show the sample file dangel.txt when opened by TextEdit and HexFiend. I also attached other sample files to be used for testing.

<img width="964" alt="dangel_on_HexFiend" src="https://user-images.githubusercontent.com/13080763/202873698-62dcff96-dfe1-4c61-ad48-e5573e12d989.png">
<img width="346" alt="dangel_on_TextEdit" src="https://user-images.githubusercontent.com/13080763/202873700-ef9c68a7-3e60-43ae-8e94-2e6a31f25b83.png">
[MSX_ShiftJIS_texts.zip](https://github.com/HexFiend/HexFiend/files/10048060/MSX_ShiftJIS_texts.zip)

**Comment by lcsacha** [comment]
Actually, it looks like better variable width support is already being worked on in the variable-byte branch (see issue #185 for more details).

**Comment by kainjow** [comment]
Also see #120
