### ISSUE TITLE
Continues crash after changing an option

### ISSUE THREAD

**Issue by spachner** [HexFiend/HexFiend#395]
Hi,

great tool! Thanks for sharing. 
I tried an option (so far I remember "group size in bytes" or so) which groups this amount of bytes in a single line. When entering 1048576 (1024*1024=1 mega byte) the tool crashes and since it stores the value somewhere I continues. Did not find where the option is store. Re-installing does no help either

Any help?

regards

spachner

**Comment by lcsacha** [comment]
This might be too late for you, but it is saved in the preferences/NSUserDefaults, and potentially in the application's saved state.

On a mac, the preferences are saved in the file "com.ridiculousfish.HexFiend.plist" in "~/Library/Preferences/" (within your user directory). You can just delete the file, or edit it in Xcode to change the value of both "BytesPerLine" and "BytesPerColumn" to something more reasonable.

The saved state (used to reopen documents/windows that were open when the application closed) would be a folder in "~/Library/Saved Application State/" named "com.ridiculousfish.HexFiend.savedState" which you can drag to the trash.

You may need to unhide your Library folder to access those folders (either by going to your user folder and using cmd-shift-period to temporarily show all the hidden items, or using the Go menu in the Finder and holding down the option key to make the Library folder show up there).

**Comment by spachner** [comment]
Thanks a lot
