### ISSUE TITLE
Templates don’t correctly do relative includes

### ISSUE THREAD

**Issue by avidrissman** [HexFiend/HexFiend#398]
Hex Fiend ships with templates built-in at `/Applications/Hex Fiend.app/Contents/Resources/templates`. However, those templates include each other, and when a template includes another template, it’s not correctly relative.

Repro:
1. Make sure you don’t have anything in `~/Library/Application Support/com.ridiculousfish.HexFiend`
2. Open a PNG file
3. From the Views menu select Binary Templates

Expected:
The shipped templates to work

Actual:
An error:

```
Include file not found: "/Users/<username>/Library/Application Support/com.ridiculousfish.HexFiend/Templates/Metadata/Exif.tcl" invoked from within
"include "Metadata/Exif.tcl"" (file "/Applications/Hex Fiend.app/Contents/Resources/templates/Images/PNG.tcl" line 7)
```

**Comment by lincerely** [comment]
Duplicated #375
