### ISSUE TITLE
Dokumentation for bit fields

### ISSUE THREAD

**Issue by schriftgestalt** [HexFiend/HexFiend#399]
I’m trying to use `uintX_bits` but I don't understand how is supposed to be set up. I have a bit field where each bit has a name and I wonder where to put the labels for each field.

**Comment by LogicalJoe** [comment]
If I am understanding your issue correctly, you want an entry for each bit in a [datatype that I will be calling a byte for simplicity].
`uint#_bits` is primarily designed to reorder bits, hence why it accepts a list of bits (I don't think I've encountered a need for this yet, but that is what it does). It does not label multiple bits, but creates one entry.
To label each bit, one can use the function multiple times as in the following:
```TCL
uint8_bits 0 "Label for bit 0"
# _bits advances the cursor so need to step back
move -1
uint8_bits 1 "Label for bit 1"
move -1
uint8_bits 2 "Label for bit 2"
# ect
```
Here are some various examples of how a procedure can be made to simplify this process:

Procedure that creates an entry for a single bit:
```TCL
# Usage: LabelBit datatype_size bit#,[bit#,[...]] label
proc LabelBit {size bit label} {
    move [expr -$size/8]
# return the bit so it can be used elsewhere if necessary
    return [uint$size\_bits $bit $label]
}

# make it look nice
section Flags {
    sectionvalue [hex 1 Flags]
    LabelBit 8 0 "Bit Zero"
    LabelBit 8 1 "Bit One"
# ect
}
```
Procedure that takes arguments for all bits:
```TCL
# Usage: LabelBit datatype_size bit#,[bit#,[...]] label [bit#,[bit#,[...]] label [...]]
proc LabelBits_args {title size args} {
    section $title {
        sectionvalue [hex [expr $size/8] Flags]
        for {set i 0} {$i < [llength $args]} {incr i 2} {
            move [expr -$size/8]
            uint$size\_bits [lindex $args $i] [lindex $args [expr $i+1]]
        }
    }
}

LabelBits_args "Flags" 8 0 "Bit Zero" 1 "Bit One"
```
Procedure that takes a list containing {bit label} tuples:
```TCL
# labelBits_list section_title datatype_size {list containing {bit, label} tuples}
proc LabelBits_list {title size bits_list} {
    section $title {
        sectionvalue [hex [expr $size/8] Flags]
        foreach tuple $bits_list {
            foreach {bit label} $tuple {
                move [expr -$size/8]
                uint$size\_bits $bit $label
            }
        }
    }
}

set list_of_bits {
    {0 "Bit Zero"}
    {1 "Bit One"}
}
LabelBits_list "Flags" 8 $list_of_bits
```
Each of these will return a template that looks like this:
<img width="312" alt="Screenshot of bit template examples" src="https://user-images.githubusercontent.com/47825483/236661476-32f9586e-9c0e-4d7d-9270-9ee01b11e6bb.png">

Hope this helps!

**Comment by schriftgestalt** [comment]
Thanks for the explanation. I thought that this would be a common use case so it should have a build in solution. But your suggestions should work for now.

**Comment by schriftgestalt** [comment]
I picked the `LabelBits_list`and modified it a bit:
```
# labelBits_list section_title datatype_size {list containing {bit, label} tuples}
proc LabelBits_list {title size bits_list} {
    section $title {
        sectionvalue [hex [expr $size/8]]
        foreach tuple $bits_list {
            foreach {bit label} $tuple {
                move [expr -$size/8]
                set bit_value [uint$size\_bits $bit]
                if {$bit_value > 0} {
                    entry $bit $label
                }
            }
        }
    }
}
```
This will produce:
<img width="288" alt="Bildschirmfoto 2023-05-07 um 11 11 45" src="https://user-images.githubusercontent.com/174660/236668569-c6f0a136-ea6b-4163-96a2-ee3cdea099c0.png">

That means it has one line per bit that is set (bit index + label). The extra "Flags" entry isn’t needed as the hex value is on the section line already.
