### ISSUE TITLE
License isn’t being detected by GitHub

### ISSUE THREAD

**Issue by avidrissman** [HexFiend/HexFiend#400]
The license on this appears to be the BSD 2-clause license, but because there are formatting differences from the standard, it’s not being picked up by the GitHub automatic licensing machinery.

Can you clean up the license and make it more stock? That way, automated tools that grant folks at tech companies permission to send PRs will note that this has an allowed license.

**Comment by superbonaci** [comment]
Add `SPDX-License-Identifier` to all files.

**Comment by superbonaci** [comment]
I think it's MIT / BSD kind of license.

**Comment by avidrissman** [comment]
It’s a BSD 2 clause license.

`SPDX-License-Identifier` isn’t the answer. Please edit the License file to clean it up and make it actually match the standard formatting of the BSD 2 clause license so that the GitHub automatic license detection system works.

**Comment by superbonaci** [comment]
Thanks!
