### ISSUE TITLE
Reference Template Field as Variable

### ISSUE THREAD

**Issue by chrissphinx** [HexFiend/HexFiend#405]
I'm not sure if this is supported by HexFiend, but I have the need to read 4 bytes as the length of a text field that follows and I'm trying to create a template that can properly read that string field. The only thing that seems to be supported though is reading a set number of characters as a string (with `str`). It seems like there's some more powerful functionality shown in the docs (ex. `[expr [pos]-4]`) but I can't figure out how I can use the already read 4 byte field as a variable inside an expression in the template files.

Is this possible or simply not supported?

**Comment by wader** [comment]
You want a single entry that has the range of both the text length and the text content? it was a while since i poked around the templates but i think you should be able to read the length and content without adding any entry and the use `entry` to add it with content and the range you want.

Something like this, but i haven't tested it:
```tcl
proc len_prefixed_text { {name ""} } {
    set l [uint32]
    set t [ascii $l]
    if { $name != "" } {
            set s [expr 4+$l]
	    entry $name $t $s [expr [pos]-$s]
    }
    return $t
}

# use like this
len_prefixed_text "title"
```
Some of the other templates might be a good source of inspiration also.

**Comment by chrissphinx** [comment]
Ah, this is a great example. I didn't realize how much of Tcl functionality could be used here. I had to add an exception if `l == 0` since apparently you cannot call `ascii` with 0 for arg:

```
proc len_prefixed_text { {name ""} } {
    set l [uint32]
    set t [ascii $l]
    if { $name != "" } {
            set s [expr 4+$l]
	    entry $name $t $s [expr [pos]-$s]
    }
    return $t
}

# use like this
len_prefixed_text "title"
```

but it's working great, thank you!

**Comment by wader** [comment]
Great! 👍

**Comment by chrissphinx** [comment]
Oops, actually, perhaps hit a real UI limitation. The text field I'm reading actually has newline characters in it and upon encountering those, the field value is just cut off. Is there a way to have the UI entries show multiple lines?

**Comment by wader** [comment]
Aha sorry don't know, but don't think i've seen multiple line values
