### ISSUE TITLE
how to remove background color

### ISSUE THREAD

**Issue by fike8016** [HexFiend/HexFiend#406]
<img width="1010" alt="Snipaste_2023-03-12_10-44-05" src="https://user-images.githubusercontent.com/127396056/224521306-7a5094c6-6494-4efc-9e9a-d6c0222efb23.png">

it is difficult to recginze selected or not.

**Comment by LogicalJoe** [comment]
You can disable individual byte coloration by unchecking `Font > Color Bytes`
<img width="382" alt="Uncolored bytes with a selection '1718191A1B1C1D1E' for demonstration" src="https://user-images.githubusercontent.com/47825483/236658630-1b0bc78e-76e1-44d0-9bd7-116439653f82.png">
But some higher-contrast selection color would be helpful.
