### ISSUE TITLE
Mach-O template does not work

### ISSUE THREAD

**Issue by mlaster** [HexFiend/HexFiend#407]
It complains about a missing import of Utility/General.tcl

**Comment by LogicalJoe** [comment]
Duplicate of #375.

You have to build it yourself to get this fix as it has not made it into a release yet.  In the meantime, you can move `Utility/General.tcl` (and probably `Metadata/Exif.tcl`) from `/Applications/HexFiend/Contents/Resources/templates/` to `~/Library/Application Support/com.ridiculousfish.HexFiend/Templates`
