### ISSUE TITLE
Opening diff view changes default window width

### ISSUE THREAD

**Issue by Siguza** [HexFiend/HexFiend#408]
Normally when you open a file and drag the window to a certain size (e.g. 0x30 bytes), all subsequent files/windows you open will inherit that size.

But if you diff two files, then the diff view will be slimmer, and that slimmer width will from then on be used as the width of new windows you open (e.g. if you chose 0x30 bytes for the two standalone windows, then the left and right columns of the diff view will both have 0x20 bytes, and if you subsequently open a file, it will get a standalone window of 0x20 bytes wide). Doing this repeatedly will quickly shrink your default window width to 0x4 bytes, which is... really not nice.

**Comment by LogicalJoe** [comment]
Duplicate of #304.

**Comment by Siguza** [comment]
Ah, you're right.
