### ISSUE TITLE
unixtime64 drops seconds from Binary Templates view

### ISSUE THREAD

**Issue by gawie-kellerman** [HexFiend/HexFiend#414]
The unixtime fields include seconds- while the Binary Templates view drops the second.  In the documentation I cannot see a simple and quick way to address this without writing additional TCL.  This decision to drop the seconds is confusing, as second accuracy is, in my opinion, not only reasonable but also the precision of the data type, and, unless I am missing something obvious, sounds like it should be the norm?

**Comment by kainjow** [comment]
unixtime commands just read an int and format its it as a date. You could use the int32 command instead if you want a raw integer.
