### ISSUE TITLE
Template Column Size

### ISSUE THREAD

**Issue by sammysmallman** [HexFiend/HexFiend#416]
Working on a template with lots of sections and sub sections the label gets cut off quite a bit.
It would be lovely to be able to resize the template column so that I can see all the labels fully.

**Comment by kainjow** [comment]
The columns are resizable and the templates view can be resized by holding down the Command key when resizing the window. Does that work?

**Comment by sammysmallman** [comment]
That works perfectly, thankyou. It's a bit of a hidden feature. It may be worth documenting somewhere. Or perhaps I missed it. Either way, thankyou.

**Comment by kainjow** [comment]
It's documented in the [release notes (under 2.14)](https://hexfiend.github.io/HexFiend/ReleaseNotes.html) and shown in the "welcome" popover that's accessible the first time you view templates or by accessing it from the templates dropdown.

**Comment by kainjow** [comment]
The window is already resizable by standard dragging and has been that way for maybe ever. Really the probably best option is some type of split view.
