### ISSUE TITLE
Date/time entry commands should all take an optional utcOffset & an output format

### ISSUE THREAD

**Issue by xyzzy-plugh-plover** [HexFiend/HexFiend#428]
Each date/time entry command (`macdate`, `fatdate`, `fattime`, `unixtime32` & `unixtime64`) should accept an optional utcOffset (that defaults to `0`) & an optional output format (that defaults to the existing output format).

**Comment by kainjow** [comment]
Do you have examples of where this would be applicable?

**Comment by xyzzy-plugh-plover** [comment]
I'm processing Apple Music DB files that include a single UTC offset that applies to all timestamps in the file. I want to apply that offset to all timestamps. I had to write a Tcl proc to do that, which I assume is less efficient than a builtin command, and my proc isn't readily available to others.

I prefer to see dates & times in ISO format.

**Comment by kainjow** [comment]
Would you have used the unixtime commands?

**Comment by xyzzy-plugh-plover** [comment]
I didn't use `unixtime**`. I used `uint32` to get the raw seconds so I could then add in the utcOffset then format in ISO. I assume I used `macdate` before I switched to `uint32`.

It looks like ISO-8601 is the date/time format I prefer to use. I don't see any other ISO date/time format, but maybe I missed something.

**Comment by kainjow** [comment]
Add initial support for the macdate command. I think I'll leave the fat ones as-is for now until they're actually needed. They format their values as just plain ints, vs macdate and unixtime which use [NSDateFormatter](https://developer.apple.com/documentation/foundation/nsdateformatter).
