### ISSUE TITLE
FR: CLI parser and/or structured export

### ISSUE THREAD

**Issue by ershov** [HexFiend/HexFiend#435]
# Feature request

I propose to add a command line interface for parsing a binary file with a template which would include both the parsed structure and corresponding offset and hex dump.

## Use cases for that

1. Post-analysis of data with other tools.
2. Streamed output can be useful for big/huge files so that there's no need to have everything in memory.

## Possible implementations

1. Native implementation in ObjC (works fast, more work)
2. TCL implementing all of HexFiend [functions](https://github.com/HexFiend/HexFiend/blob/master/templates/Reference.md) (slower performance, quick to do)

**Comment by wader** [comment]
Hey, here is a prototype of a TCL implementation https://github.com/wader/textfiend which is partly what became https://github.com/wader/fq

**Comment by ershov** [comment]
@wader thank you for the links. textfiend unfortunately doesn't work for me. It just exists without any visible effect. It might be because it doesn't implement `include` and doesn't have any error reporting.

**Comment by wader** [comment]
@ershov Yeap probably so, it lacks a lot of functionality. But feel free to continue on it or copy from it you like

Ddo you have the TCL code for your decoder somewhere? can have a quick look if it's something simple

**Comment by kainjow** [comment]
Seems like a cool idea, probably for a separate project though. I have been thinking about making the all the parser/Tcl stuff it's own library, which would help with something like this.

**Comment by ershov** [comment]
Hey just for reference: [my implementation](https://github.com/wiredtiger/wiredtiger/blob/develop/tools/hexfiend/Templates/hexparse).
