### ISSUE TITLE
Bug: Nested section error handling

### ISSUE THREAD

**Issue by ershov** [HexFiend/HexFiend#439]
## Bug description

With nested sections, if the error is caught at higher levels, the section context doesn't go to the outer scope. This makes error recovery complicated (but not impossible, thanks TCL).

## To reproduce:

```tcl
proc parse_blah {} {
  section "AAA" {
    entry AAA v1
    section BBB {
      entry AAA:BBB v1
      error Oops
      entry AAA:BBB v2
    }
    entry AAA v2
  }
}
entry top v1
if {[catch parse_blah]} { entry "Error" $errorInfo }
entry top v2
```

### Expected result:
<img width="255" alt="image" src="https://github.com/HexFiend/HexFiend/assets/449936/958ee3bb-7740-487a-b0cf-51d99e4b0d0f">

### Actual result:
<img width="257" alt="image" src="https://github.com/HexFiend/HexFiend/assets/449936/dca18751-6ac5-4021-b836-ae4be06d2f61">

... and further template processing happens inside the wrong section.

## Possible Fix

Each section should catch errors in it and properly unwind the section stack until it's caught. I not sure if it can be done more efficiently in ObjC but in TCL it could wrap each section in code like:

```tcl
section SECTION_NAME SECTION_BODY  -->

if {![section SECTION_NAME {
  if {[catch {
    **SECTION_BODY**
    expr 1
  }]} {
    entry "Error at [pos]" **SECTION_NAME**:$errorInfo
    expr 0
  }
}]} {
  error "**SECTION_NAME**:$errorInfo"
}
```

What this code is doing is - it always catches all errors inside of the sections, and converts them into a return code from the `section` call, then outside of the section rethrows the error if there is any (with added information of where the error happened.

Here is what it does to the example code:

<img width="316" alt="image" src="https://github.com/HexFiend/HexFiend/assets/449936/3bb99c90-5afc-4977-b848-9c92e0caaf34">

Note that even if some sections are collapsed, there's still useful information about the error:

<img width="309" alt="image" src="https://github.com/HexFiend/HexFiend/assets/449936/f6d8b508-b9e5-4e6d-b8a0-549eb0ed07d5">

Here is the actual implementation that I use for myself:

```tcl
proc xd {x} { format "0x%X (%d)" $x $x }
proc dx {x} { format "%d (0x%X)" $x $x }

proc ssection {args} {
  global errorInfo
  parseIfOkErrArgs "" default
  if {[llength $args] < 2} { error "ssection needs at least 2 args: name, body" }
  set sectionName "?:"
  foreach arg $args {
    if {![string match "-*" $arg]} {
      set sectionName "$arg:";
      if {$ifErr eq "default"} { set ifErr "global errorInfo; error \"$sectionName\$errorInfo\"" }
      break
    }
  }

  set catchCode [join [list {
    global errorInfo
    entry "ERROR \[[dx [pos]]\]" "} $sectionName {$errorInfo" 1 [expr {[pos] < [len] ? [pos]-1 : [len]-1}]
    expr 0
  }] ""]
  set body [lindex $args end]
  set body [list if "\[[list catch "$body\nexpr 1"]\]" $catchCode]
  set sectionCall [list section {*}[lreplace $args end end $body]]
  set sectionCallWrap [join [list $sectionCall {expr 1}] "\n"]
  set callRes [uplevel 1 $sectionCall]
  if {$callRes eq "" || $callRes} {
    if {$ifOk ne ""} { return [uplevel 1 $ifOk] } else { return 1 }
  } else {
    #error $errorInfo
    if {$ifErr ne ""} { return [uplevel 1 $ifErr] } else { return 0 }
  }
}

proc parseIfOkErrArgs {{ifOk ""} {ifErr ""}} {
  uplevel 1 [list lassign [list $ifOk $ifErr] ifOk ifErr]
  uplevel 1 {
    while {1} {
      switch -- [lindex $args end-1] {
        && { set ifOk [lindex $args end]; set args [lrange $args 0 end-2] }
        || { set ifErr [lindex $args end]; set args [lrange $args 0 end-2] }
        default break
      }
    }
  }
}

```

and the template fragment being like:

```tcl
proc parse_blah {} {
  ssection "AAA" {
    entry AAA v1
    ssection BBB {
      entry AAA:BBB v1
      error Oops
      entry AAA:BBB v2
    }
    entry AAA v2
  }
}
uint8  ;# do some parsing for proper [pos]-1 offset
entry top v1
if {[catch parse_blah]} { entry "Error" $errorInfo }
entry top v2
```

`&&` and `||` blocks can be used for additional code in case of error or success like this:

```tcl
proc parse_blah {} {
  ssection "AAA" {
    entry AAA v1
    ssection BBB {
      entry AAA:BBB v1
      error Oops
      entry AAA:BBB v2
    } || {}
    entry AAA v2
  }
}
uint8  ;# do some parsing for proper [pos]-1 offset
entry top v1
if {[catch parse_blah]} { entry "Error" $errorInfo }
entry top v2
```

resulting in:

<img width="285" alt="image" src="https://github.com/HexFiend/HexFiend/assets/449936/5197973d-6966-459c-986e-8b0f3e19b2dd">

a convenient error recovery across sections at all levels.

The reason for extracting `parseIfOkErrArgs` into a separate function is that I have a similar implementation of `main_guard` to handle errors of arbitrary code, not only sections which is a separate feature request in case if it appears to be interesting.

**Comment by kainjow** [comment]
Thanks for the details! I think I see the issue.
