### ISSUE TITLE
FR: Include failed assertion in "Template not applicable" message

### ISSUE THREAD

**Issue by nneonneo** [HexFiend/HexFiend#440]
It would be nice if the message "Template not applicable" could include the reason why it is not applicable (e.g. "Template not applicable: Bytes at offset 0 not equal to 4A 4B 4C 4D"). Currently, a very detailed error is produced if a template fails to execute, but the "Template not applicable" message is comparatively sparse.

One use-case here is where a template contains a requirement for, say, one particular version or variant of a file format, but you want to handle a different version or variant of the same format. In this case, it would be useful to know which assertion (requirement) is failing so it can be corrected.

**Comment by kainjow** [comment]
Good idea, added it based on your suggestion.
