### ISSUE TITLE
Upgrade the Compare Feature with biodiff

### ISSUE THREAD

**Issue by LogicalJoe** [HexFiend/HexFiend#448]
Because the comparer is slow and not super useful for files larger than a hundred megabytes on my system, it potentially could be upgraded using a variation of biodiff in addition to a template comparer.
https://github.com/8051Enthusiast/biodiff

(Yes, I know Range Compare exists, but generally there's enough misalignment that it's not as useful as I would like it to be, enough so that it could have its own issue, but it'd be better, though more time-consuming, to overhaul the whole thing.)

**Comment by kainjow** [comment]
That’s a Rust project, and while I’m a fan of the language, I don’t want to add its toolchain into HF, as one of the goals of this project is to use Apple technologies as much as possible.
