### ISSUE TITLE
Adding custom encoding

### ISSUE THREAD

**Issue by og2t** [HexFiend/HexFiend#478]
Hi! I've been using HexFiend for a while and it's been great.

What I am missing is to add a custom text encoding, e.g. I would like to be able to use [PETSCII](https://en.wikipedia.org/wiki/PETSCII) 

Is it possible to add custom encoding file/template?

Cheers!

**Comment by kainjow** [comment]
There is basic support but I believe only documented in this older comment:
https://github.com/ridiculousfish/HexFiend/issues/95#issuecomment-397858715
