### ISSUE TITLE
Question about "open with"

### ISSUE THREAD

**Issue by nospam2k** [HexFiend/HexFiend#481]
I'm sorry to put this here as I'm not sure where I should ask this.

I noticed that hex fiend shows up a lot in "open with". I am so sick of TextEdit being the only option for many files that don't have extensions and I'd like to know how HexFiend is able to register itself to files without extensions so I can avoid having to go through the "other > choose a file" menu for other more appropriate editor apps.

Thank you for your help in advance!

**Comment by kainjow** [comment]
It’s done through the Info.plist file
https://github.com/HexFiend/HexFiend/blob/baa4ad0a55d000281e09e2ef68a4461062c88854/app/Info.plist#L47
