### ISSUE TITLE
Not displaying character ü (C3BC) in UTF-8

### ISSUE THREAD

**Issue by JDS-Teacher** [HexFiend/HexFiend#490]
<img width="454" alt="image" src="https://github.com/user-attachments/assets/f04c9f89-35c7-41c9-98f4-d8cc3c5800ea">

Apparently in UTF-8 this character is not displayed correctly (or am I using the program wrong)?

**Comment by kainjow** [comment]
This is not implemented yet. See https://github.com/HexFiend/HexFiend/issues/185
