### ISSUE TITLE
Resolve symlinks in Templates folder

### ISSUE THREAD

**Issue by lafkpages** [HexFiend/HexFiend#492]
I tried using symlinks in the Templates folder, so I could keep my templates in sync with the ones in this repo, which I've cloned locally. However, Hex Fiend seems to ignore directories that are symlinks.

I tried putting a `templates` symlink inside Hex Fiend's `Templates` directory pointing to this repo's `templates`, but it got ignored. I also tried removing my `Templates` directory and symlinking the entire thing to this repo's `templates`, but that also didn't work.

I ended up just copying all the files over, but that's not ideal since if the templates in this repo are updated and I pull the changes, I will probably forget to copy them to my Templates folder and they won't get updated.

**Comment by kainjow** [comment]
I think this should be working as of version 2.15. What version are you using?

**Comment by lafkpages** [comment]
Alright, I upgraded to 2.18 and it works now. Sorry, I thought I searched for this before making the issue 😅
