### ISSUE TITLE
Compare window opens (technically) but is not visible (due being positioned offscreen)

### ISSUE THREAD

**Issue by porg** [HexFiend/HexFiend#493]
## Reproduction
1. Open File 1
2. Open File 2
3. Menu → File → Compare Front Documents `⌘ ⇧ D`
- **Expected:** I get the comparison window.
- **Actual:** The comparison window opens, but it is not visible.

## Analysis

- In Menu → Window: That windows is listed and ticked
- In App Expose (swipe down with three fingers) that window is there, but only shows the title, no content
- In Mission Control it does not show up at all (I scrolled over all empty space too in order to identify it that way, to no avail)
- It is also not on another Desktop (which I rarely use)
- It is also not on the other display. I usually use my MacBook Pro with the internal 15'' display plus an external 1920x1080 screen.
- The bug occurs regardless of whether I use a single or dual screen setup.

## Environment
- HexFiend 2.18
- macOS 13.6.9 Ventura
- On MacBook Pro Retina 15.4'' (Mid 2014) with OCLP 2.0.1
- Possibly OCLP is the cause, although I doubt it, as I had no issues with graphics acceleration or window management at all.

https://github.com/user-attachments/assets/84487169-160c-4d48-ac3e-be8c821d53f6

**Comment by kainjow** [comment]
It looks like it's this issue still https://github.com/HexFiend/HexFiend/issues/457which means there's still a change in 2.18 that's causing this that didn't get reverted.

**Comment by kainjow** [comment]
Should be fixed now. Please test out this beta and if all good I'll make it official https://github.com/HexFiend/HexFiend/releases/tag/v2.18.1b1

**Comment by porg** [comment]
Tested v2.18.1
- ✅ When triggering th compare command the corresponding comparison window opens.
- ❌ But the the options in Menu > Views only apply to the right panel. The left panel is shown in HEX only. 🙁 
  - So the good improvement from https://github.com/HexFiend/HexFiend/issues/359#issuecomment-2406918037 is gone.
  - So I personally would rather use v2.18 and get that compare window which uses the view options in both panels and use the workaround to get the comparison window which seems to be placed somewhere offscreen.
